language: scala

scala:
  - "2.13.1"
  - "2.12.10"
  - "2.11.12"

sudo: false

script: $TRAVIS_BUILD_DIR/travis/script/build.sh

jdk:
  - oraclejdk13

cache:
  directories:
    - $HOME/.m2
    - $HOME/.ivy2
    - $HOME/.sbt

git:
  submodules: false

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

env:
  global:
  - secure: UM06xGipLOWB23f17Um8TatW6yGz2G1DNjOsLsboo0oAl91fw9EWNNQH6uVO/JxMSQhjRJyV2aDVkLNyRwF+aq8VDeUvt+QV5hLiG+XGxJF3J/vl8QWkx7ieLbhF6DxJWmtSnpO5uXQZdQhAJ/hvR96pHbwKS0IEoeXyXAcGj4YaIclwN1THa5V+y7pTUlLqIlKD9eFF0bCI55tm7p28tkBIz+dBdjfVASJGmo+heapOcoSo82wxszN5lkx8BcQQibElNglAWNSD7UjLrAdkCqWZfAIs+IOfI+jqp2gu2nJBoh0dh6wajYiTYmznFK2CsALgeXQR086uAIIRhOB9bQ1b9TerSjVyHLfBDXcs0ue1AbzwUtAeoz3o4rd3+AO3rOfO83d7cpi90R+Aa5QJPC/961ogx6cbRnPlHzDSwSq6s0ePa6LfijgmH6tlGjLnTC9O7igiUKIKCwVh8DYQ8HR/+MoZj1rIop+CnMY6vF2ONYeZVVss3jAsQwKYe17mhRjZUYFMmQePEiqb2RJkFFmk2TnBUDoc8HT2p8xnc1nR+S0+iWertD3WAXMM6NW8DVNayuwZfN26tOe5ZdVxqpXZ+IEV/1bgGRrOJCDAzhShaW6TTBQo7VJFJLW7BUKMHlE3cFQENpEzQuqZRFLhusQzfMFmYjHwupzLQ/cXE6o=
  - secure: DmV10oATjsbIImDT2iHIFDrN3sPUhcG7CLjpqEQipRYpsEtt5g8rtsRvyFXAwrU8KrCDRlXDDEVy6FMf53p5ROxrySqE4vnX872bdkhtH7BLkfXrN4/gSoGhUWg8kiG1nhdAFzBJ0uSDz49zsPxB6JIAS3vicxE8reFfEp71FCtpMBhaW2tIHGZ4OnOFjx0AGYAs9sIQhnwbaJc/cRC2k/BITjFSCBMrsjtIcKkSPWEwgPqoU8EKqJr9+xiFLSnYI9Uu2qdJLSDVZ8pJotnpGMePI01v2ayfU2OVc3Wnd9NgwbX3x6d/JP/mtlVZ/e0hHl1oINofRmVAJeiCMbUSEv4XBBN0e+AMp2DU78eu+7kLJqj95KrDMiTy2FREEabFAQ2XC0K0hXn24p2oj0dTGbtSRVc4hjf1u2zpAaBjRc/JuRVzkQZ/X+t2Jl/KncZKCYNTTAaiCWJyb6RqU4mNAZVEQ+8RZYZqtuJX4jiCb0EvZn6+vciZk+dTdDcr2BFZj3CtccQAw4TLlmbGHU30+FKwGImqhKZmdk2MNnIFpPQ3y11x9iJZbd6wQXVioa4r1ohfBuQgGSLsP6K77CNKySo5DlisLPJjckvbqfzAOh17pCLaEPA2gvp5ur2EYRafsCeXOnLlek5bLP6hsdNzhH4QdHvF8uS92FTystg8oDs=
  - secure: TdHVFfqrlSCUBaV0ehFzxIjjj8s4aM6joJEBB9qgwBtzpAjpZLZvKyPaRW/QGrUiKTA3XXwSg2fAay9hvCBxxmrjZd41+yFwElPT9NVM+MmT3RvvpFxlUAIwqnnK0hxvLDnCVxAx6GSy2uwE4e/981gfywjngsAP9dOSFaAFsO7u1R5BNuM3usIxKHiKpZ7+uYi++RvJIYPZ1jHlSjjJC5+cYcQ58/CdWjy0YZ7y4fNLU8KkkEDDS08MSvq58hkaIenPY8MYAt2M3nqgPzG1zESkXMSDbQ5xl30+AGecQkeC+qMxM3f1b6zbkiX9/eSlFmzwT4dUbEAg9ks8X/ynvNJ11NW+Htg6PO4pn3DubUri6SHVkTYwdm5uK+Xg2BMvCEA8AcUXsb9nCNYqNNt6enVEtL1CkccqghCcQ1Qr2TKMJy4xf4IhdjqwehAU+jnlFnVw/GqcbL+f2Qeoivh3FLjW1o0wrf7CiQGO3dAWBFCYcd3ntiEvmpHavjLrVV05gg7NdYoPkmlaac1TaDxT+nuNou7yGDeAReXVLwyE2yflcYhXeV0TXP3CtdF4aRzPaq7pI+X+PBIi06u+KpNWQ+DyP0T5eE8WgHQvs6afQs9Pd5/UjIYJMAevPZx4r8bGgLWDuK7cfow4EP2skEVUfe6QGG5v/fgZcB404Bn8igQ=
  - secure: QnaasCJ538AWBMOF7vFv2j4m4mz4i+DMoAcztozLtUMOC3qL0g7Bi4lPgGG3ASuk6WQEFO3Tr9SGK9GZ053enmpmbtC9udY+l/EDXqhC3sIti89eAERGBe7yqG6M0iYKtUg9FhJJiMik//5nMzRZ+q+zlUkvnrKnIq6zPFOixKwoQheYl3cQETjD1tG2iiH3qG2VZYZck9iVjL+bktnvs3hRzDKN+GuXfT4ETqH8JLnz9kaV0sCeQtrGiASWrQCYbgWMYzbHsexNe8TqCcPHvAiBXlTseyf4M/sh9PjFo0DWIprxRPCEh0AC8gd3Oko3MCWFzJ5UaYZDqcyDCxJ66G/wdNd5V7SERqsrKx5CnzV4fWfagPukdKMRrazYJEo0Gu6a3jUAZ+Qoh/Hm21CBZ0/fNoGsAY0gbLMvKa/Dv9ZBeQBO0qs5Vb1IZwOhdrvbHum/KLqPYKcp3zRcX2ejr7KOI57qrr7jRJUqVroPWRMw3/SSrKrmmjpRvZJZ59Lesb7obXAjBfduxDYtBtxabQyKPNgBD59si/s8urS9IqR2fi7jWLRj7gB76tTEvLsVxYDo7s6p8CLFnF6sDX66lkcP2BvFbgqVsL0rE+BM+OyInm+4DqMm9hM8VB3hF4UzIwU9r3Je7WODCzARbwkCVC3uyt+1uRdrEEzNO83moCc=
